image: node:18.16.0

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g @nestjs/cli

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script:
    - npm run test:cov
  allow_failure: true

# deploy:
#   stage: deploy
#   environment:
#     name: production
#   script:
#     - pm2 stop adam-onboard-app
#     - pm2 delete adam-onboard-app
#     - npm run pm2:start:prod
#     - pm2 update
#     - pm2 save
